Update Aaroz-web/Chictastic script.js. Keep all existing destination data, selection logic, planner logic, and language switcher unchanged. Replace the current Wikipedia REST thumbnail image system with a curated Wikimedia Commons image search system for the 57 destination cards. The goal is attractive travel photography, not flags, signs, generic streets, museums as buildings, or random city thumbnails.

For each destination, define a DESTINATION_IMAGE_QUERIES object with a specific scenic/landmark search phrase. Use visually strong subjects such as beaches, viewpoints, skylines, famous architecture, mountains, lakes, bays, sunsets, etc. Examples:
Barcelona: "Barcelona Sagrada Familia skyline"
Malaga: "Malaga Alcazaba sea view"
Valencia: "Valencia City of Arts and Sciences"
Mallorca: "Mallorca Cap de Formentor"
Rooma: "Rome Colosseum sunset"
Bologna: "Bologna skyline red rooftops"
Florence: "Florence Duomo panorama"
Sardinia: "Sardinia La Pelosa beach"
Sisilia: "Sicily Taormina Mount Etna sea"
Ateena: "Athens Acropolis sunset"
Kreeta: "Crete Balos beach"
Rodos: "Rhodes Lindos beach"
Korfu: "Corfu Paleokastritsa bay"
Mykonos: "Mykonos Little Venice sea"
Lisbon: "Lisbon viewpoint sunset"
Porto: "Porto Douro Dom Luis bridge sunset"
Algarve: "Algarve Benagil cave beach"
Berliini: "Berlin Brandenburg Gate sunset"
Hampuri: "Hamburg harbor Elbphilharmonie sunset"
München: "Bavaria Neuschwanstein Castle Alps"
Amsterdam: "Amsterdam canals sunset"
Vienna: "Vienna Schonbrunn Palace gardens"
Zürich: "Zurich lake Alps panorama"
Geneva: "Geneva lake Jet d'Eau Alps"
Praha: "Prague Charles Bridge sunset"
Luxembourg: "Luxembourg city valley panorama"
Alppikylät: "Matterhorn Zermatt Alps"
Reykjavik: "Iceland Reykjavik mountains ocean"
Oslo: "Oslo fjord Opera House sunset"
Bergen: "Bergen Norway fjord viewpoint"
Kööpenhamina: "Copenhagen Nyhavn sunset"
Tukholma: "Stockholm archipelago sunset"
Gothenburg: "Gothenburg Sweden harbor sunset"
Helsinki: "Helsinki Suomenlinna sea sunset"
Turku: "Turku Finland archipelago castle"
Dublin: "Dublin Cliffs of Moher Ireland"
Lontoo: "London Tower Bridge Thames sunset"
Pariisi: "Paris Eiffel Tower sunset"
Nizza: "Nice France Promenade des Anglais Mediterranean"
Bordeaux: "Bordeaux Place de la Bourse water mirror"
Bruges: "Bruges Belgium canals sunset"
Rotterdam: "Rotterdam Erasmus Bridge skyline sunset"
New York: "New York skyline Statue of Liberty sunset"
Los Angeles: "Los Angeles Griffith Observatory skyline sunset"
Dallas: "Dallas skyline sunset Reunion Tower"
Alaska: "Alaska mountains glacier landscape"
Toronto: "Toronto skyline Lake Ontario sunset"
Miami: "Miami South Beach ocean sunset"
Buenos Aires: "Buenos Aires skyline sunset Puerto Madero"
Rio de Janeiro: "Rio de Janeiro Copacabana Sugarloaf sunset"
Sapporo: "Sapporo Japan mountain city view"
Tokio: "Tokyo skyline Mount Fuji sunset"
Seoul: "Seoul skyline Namsan sunset"
Singapore: "Singapore Marina Bay Gardens by the Bay night"
Sydney: "Sydney Opera House Harbour sunset"
Auckland: "Auckland New Zealand skyline harbor sunset"
Wellington: "Wellington New Zealand harbor hills sunset"

Implement loadDestinationImage(image, city) using the Wikimedia Commons API, not Wikipedia article summaries. Query Commons with the destination-specific phrase, namespace 6, get up to 10 results, imageinfo URL/thumburl. Pick the first usable raster image while rejecting titles containing obvious bad terms like flag, map, logo, icon, symbol, coat of arms, sign, street sign, road sign, bus stop, station sign. Prefer landscape images where possible. Use thumburl width around 900. If the API fails, keep a neutral placeholder. Add loading/loaded classes if useful. Remove WIKI_DESTINATION_NAMES and the old Wikipedia functions entirely.

Do not change any other site functionality. Make the image cards continue to render immediately with a neutral placeholder and then replace each background with the real Commons image when loaded. Return the updated complete file.